# builds the demo client with the latest development version of the sdk published to the github package repository
FROM node:10-alpine as builder
ARG NODE_AUTH_TOKEN

WORKDIR /app

COPY package.json yarn.lock ./
COPY .npmrc ./
RUN yarn upgrade --scope @kiltprotocol --latest

COPY . ./
RUN yarn build:devnet

FROM nginx:alpine
COPY --from=builder /app/build/ /usr/share/nginx/html/
COPY --from=builder /app/config/nginx.conf /etc/nginx/conf.d/default.conf
