FROM node:10-alpine as builder

WORKDIR /app
RUN apk add yarn

COPY package.json yarn.lock ./
RUN yarn install

COPY . ./
RUN yarn lint
#RUN yarn testCI
RUN yarn build:devnet

FROM nginx:alpine
COPY --from=builder /app/build/ /usr/share/nginx/html/
COPY --from=builder /app/config/nginx.conf /etc/nginx/conf.d/default.conf
