version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=registry
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
  services:
    image: kiltprotocol/demo-services
    environment:
      - NODE_ENV=docker-compose
      - MONGODB_HOST=mongodb
      - MONGODB_USER=mongoadmin
      - MONGODB_PASS=secret
      - FAUCET_ACCOUNT=faucet
      - BOOT_NODE_ADDRESS=ws://mashnet-node:9944
    ports:
      - 3000:3000
  mashnet-node:
    image: kiltprotocol/mashnet-node
    ports:
      - 9944:9944
    command: ./target/release/mashnet-node --dev --ws-port 9944 --ws-external
  client:
    build:
      context: .
      dockerfile: docker.dependencies_only
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_SERVICE_HOST=//127.0.0.1
      - REACT_APP_SERVICE_PORT=3000
      - REACT_APP_NODE_HOST=127.0.0.1
      - REACT_APP_NODE_WS_PORT=9944
      - REACT_APP_FAUCET_URL=https://faucet.kilt.io
      - PUBLIC_URL=.
    ports:
      - 3001:3001
    command: yarn start
